---
version: "3.7"

services:
  service:
    image: docker-challenge
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    networks:
      - example
    deploy:
      replicas: 1
    configs:
      - source: name
        target: /name.txt
  service2:
    image: docker-challenge
    ports:
      - target: 8080
        published: 8081
        protocol: tcp
        mode: host
    networks:
      - example
    deploy:
      replicas: 1
    configs:
      - source: name
        target: /name.txt

configs:
  name:
    file: ./name.txt

networks:
  example:
